#!/bin/ksh

[ $# -eq 2 ] && dest=$2
[ $# -eq 1 ] && dest=$1
[ $# -eq 0 ] && echo "Please enter the hostname to rsh to: \c" && read dest
alias xdt='toolwait dtterm -xrm "*menuBar: False" -sl 5000 -name'
octet=`nslookup $dest | sed -n '5p' | awk -F: '{print $2}' | awk -F\. '{print $3}'`
[ $octet -ne 60 -a $octet -ne 7 -a $octet -ne 58 ] && xdt $dest -e /usr/bin/rsh $dest || xdt $dest -e /usr/dist/exe/ssh $dest
#[ $# -le 1 ] && getksh
