#!/usr/bin/python

import commands

df_cmd = commands.getoutput("df -hP")
lines = df_cmd.splitlines()
print ("Filesystem\tSize\tAvail\tUsed\tMounted on").expandtabs(30)
for line in lines[1:]:
	columns = line.split()
	filesystem = columns[0]
	size = columns[1]
	used = columns[2]
	available = columns[3]
	used = columns[4]
	mounted = columns[5]
	tup = (columns[0], columns[1], columns[2], columns[3], columns[4], columns[5])
	output = str(tup)
	print(output).expandtabs(30)
	
print "%s\t%s\t%s\t%s\t%s\t%s " % (columns[0], columns[1], columns[2], columns[3], columns[4], columns[5])